using System;

using Match3.Core.Generation;
using Match3.Core.Grid;
using Match3.Core.Matching;
using Match3.Core.Moves;
using Match3.Core.Randomness;

using Xunit;

namespace Match3.Core.Tests.Generation
{
    public class BoardGeneratorTests
    {
        [Fact]
        public void Generate_Seed1_ProducesReferenceBoard()
        {
            // Generated by an independent implementation of the documented fill rule. If this changes,
            // replays recorded with earlier builds would start from a different board.
            Board board = BoardGenerator.Generate(4, 4, new SeededRandom(1));

            AssertBoard(
                """
                KYRK
                GBGG
                RPGP
                BPYK
                """,
                board);
        }

        [Fact]
        public void Generate_FirstAttemptDeadlocked_RetriesWithTheSameRandomSequence()
        {
            // Seed 31's first 4x4 board has no legal move; this is the second attempt.
            Board board = BoardGenerator.Generate(4, 4, new SeededRandom(31));

            AssertBoard(
                """
                GYGK
                PPGB
                PKRB
                GPRY
                """,
                board);
        }

        [Theory]
        [InlineData(8, 8)]
        [InlineData(5, 7)]
        [InlineData(10, 4)]
        [InlineData(3, 3)]
        public void Generate_ManySeeds_BoardsHaveNoMatchesAndAtLeastOneLegalMove(int width, int height)
        {
            for (ulong seed = 0; seed < 200; seed++)
            {
                Board board = BoardGenerator.Generate(width, height, new SeededRandom(seed));

                Assert.Equal(width, board.Width);
                Assert.Equal(height, board.Height);
                Assert.Empty(MatchFinder.FindMatches(board));
                Assert.NotEmpty(MoveFinder.FindLegalMoves(board));
            }
        }

        [Fact]
        public void Generate_SameSeed_ProducesSameBoard()
        {
            Assert.Equal(
                BoardGenerator.Generate(8, 8, new SeededRandom(5)),
                BoardGenerator.Generate(8, 8, new SeededRandom(5)));
        }

        [Fact]
        public void Generate_BoardTooSmallForAnyMove_ThrowsInvalidOperation()
        {
            Assert.Throws<InvalidOperationException>(() => BoardGenerator.Generate(2, 2, new SeededRandom(1)));
        }

        [Theory]
        [InlineData(0, 8)]
        [InlineData(8, 0)]
        [InlineData(-1, 8)]
        public void Generate_NonPositiveDimension_ThrowsArgumentOutOfRange(int width, int height)
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => BoardGenerator.Generate(width, height, new SeededRandom(1)));
        }

        [Fact]
        public void Generate_NullRandom_ThrowsArgumentNull()
        {
            Assert.Throws<ArgumentNullException>(() => BoardGenerator.Generate(8, 8, null!));
        }

        private static void AssertBoard(string expected, Board actual) =>
            Assert.Equal(BoardNotation.Format(BoardNotation.Parse(expected)), actual.ToString());
    }
}