using System;
using System.Linq;

using Match3.Core.Randomness;

using Xunit;

namespace Match3.Core.Tests.Randomness
{
    public class SeededRandomTests
    {
        // Generated by an independent SplitMix64 implementation. If this changes, replays recorded
        // with earlier builds would no longer reproduce.
        private static readonly int[] Seed42Reference = { 413, 291, 858 };

        [Fact]
        public void NextInt_Seed42_MatchesReferenceSplitMix64Sequence()
        {
            var random = new SeededRandom(42);

            Assert.Equal(Seed42Reference, new[] { random.NextInt(1000), random.NextInt(1000), random.NextInt(1000) });
        }

        [Fact]
        public void NextInt_SameSeed_ProducesSameSequence()
        {
            Assert.Equal(Draw(seed: 7), Draw(seed: 7));
        }

        [Fact]
        public void NextInt_DifferentSeeds_ProduceDifferentSequences()
        {
            Assert.NotEqual(Draw(seed: 1), Draw(seed: 2));
        }

        [Theory]
        [InlineData(1)]
        [InlineData(6)]
        [InlineData(1000)]
        public void NextInt_ManyDraws_StayWithinRange(int maxExclusive)
        {
            var random = new SeededRandom(123);

            for (int i = 0; i < 1000; i++)
            {
                int value = random.NextInt(maxExclusive);
                Assert.InRange(value, 0, maxExclusive - 1);
            }
        }

        [Theory]
        [InlineData(0)]
        [InlineData(-5)]
        public void NextInt_NonPositiveMax_ThrowsArgumentOutOfRange(int maxExclusive)
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => new SeededRandom(1).NextInt(maxExclusive));
        }

        private static int[] Draw(ulong seed)
        {
            var random = new SeededRandom(seed);
            return Enumerable.Range(0, 20).Select(_ => random.NextInt(1000)).ToArray();
        }
    }
}